/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import Dialog.ClienteDialog;
import Modelos.Cliente;
import Modelos.FileManager;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author rocio
 */
public class ListaClientes extends javax.swing.JFrame {

    private DefaultListModel<String> modelClientes;
    private javax.swing.JList<String> listaClientes;

    /**
     * Creates new form Listalientes
     */
    public ListaClientes() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Lista de Clientes");

        modelClientes = new DefaultListModel<>();
        listaClientes.setModel(modelClientes);
        cargarClientesDesdeArchivo();
    }

    private void cargarClientesDesdeArchivo() {
        modelClientes.clear();
        try {
            ArrayList<Cliente> clientes = (ArrayList<Cliente>) FileManager.cargarClientes("clientes.txt");
            for (Cliente c : clientes) {
                modelClientes.addElement(c.getNombre() + " " + c.getApellido());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se pudo cargar la lista de clientes.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Editar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Añadir = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Añadir.setText("Añadir");
        Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(297, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Editar)
                    .addComponent(Eliminar)
                    .addComponent(Añadir)
                    .addComponent(salir))
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 164, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Editar)
                .addGap(18, 18, 18)
                .addComponent(Eliminar)
                .addGap(18, 18, 18)
                .addComponent(Añadir)
                .addGap(26, 26, 26)
                .addComponent(salir)
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        // TODO add your handling code here:
        int selectedIndex = listaClientes.getSelectedIndex();
        if (selectedIndex != -1) {
            String actual = modelClientes.getElementAt(selectedIndex);
            String nuevo = JOptionPane.showInputDialog(this, "Editar nombre del cliente:", actual);
            if (nuevo != null && !nuevo.trim().isEmpty() && nuevo.matches("[a-zA-Z ]+")) {
                try {
                    ArrayList<Cliente> clientes = (ArrayList<Cliente>) FileManager.cargarClientes("clientes.txt");
                    String[] partes = nuevo.split(" ");
                    if (partes.length >= 2) {
                        clientes.get(selectedIndex).setNombre(partes[0]);
                        clientes.get(selectedIndex).setApellido(partes[1]);
                        FileManager.cargarClientes("Clientes.txt");
                        cargarClientesDesdeArchivo();
                    } else {
                        JOptionPane.showMessageDialog(this, "Ingrese nombre y apellido.");
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error al editar el cliente.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "El nombre debe contener solo letras.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente para editar.");
        }

    }//GEN-LAST:event_EditarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Cierra la ventana actual
     
    }//GEN-LAST:event_salirActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        int selectedIndex = listaClientes.getSelectedIndex();
        if (selectedIndex != -1) {
            try {
                ArrayList<Cliente> clientes = (ArrayList<Cliente>) FileManager.cargarClientes("clientes.txt");
                clientes.remove(selectedIndex);
                FileManager.cargarClientes("clientes.txt");
                cargarClientesDesdeArchivo();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar cliente.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente para eliminar.");
        }


    }//GEN-LAST:event_EliminarActionPerformed

    private void AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirActionPerformed
        // TODO add your handling code here:
        ClienteDialog dialog = new ClienteDialog(this, true);
        cargarClientesDesdeArchivo();
    }//GEN-LAST:event_AñadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Añadir;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
