/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dialog;

import Modelos.FileManager;
import Modelos.Cliente;
import java.awt.GridLayout;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author rocio
 */
public class ClienteDialog extends javax.swing.JDialog {

    /**
     * Creates new form ClienteDialog
     */
     public ClienteDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarComponentes(); 
     }
     
     
    private void inicializarComponentes() {
        // Configuro el titulo de la ventana
        setTitle("Registrar Cliente - CinesRosio");
        setSize(400, 250); // Tamaño de la ventana
        setLocationRelativeTo(null); // Centro la ventana en la pantalla
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); // cierro la ventana si le doy al boton

        // Establecer un GridLayout de 6 filas y 2 columnas
        setLayout(new GridLayout(6, 2));

        // Creo los componentes
        JLabel nombreLabel = new JLabel("Nombre:");
        JTextField nombreField = new JTextField();

        JLabel apellidoLabel = new JLabel("Apellido:");
        JTextField apellidoField = new JTextField();

        JLabel emailLabel = new JLabel("Email:");
        JTextField emailField = new JTextField();

        JLabel telefonoLabel = new JLabel("Teléfono:");
        JTextField telefonoField = new JTextField();

        JButton guardarButton = new JButton("Guardar");

        // Añado los componentes
        add(nombreLabel);
        add(nombreField);

        add(apellidoLabel);
        add(apellidoField);

        add(emailLabel);
        add(emailField);

        add(telefonoLabel);
        add(telefonoField);

        add(new JLabel()); // añado espacio vacio
        add(guardarButton); // Boton de guardar

        guardarButton.addActionListener(e -> {
    String nombre = nombreField.getText();
    String apellido = apellidoField.getText();
    String telefono = telefonoField.getText();
    String email = emailField.getText();

    // controlar que solo tenga letras
    if (!nombre.matches("[a-zA-Z]+")) {
        JOptionPane.showMessageDialog(null, "El nombre debe tener solo letras.");
        return;
    }

    // que el apellido solo tenga letras
    if (!apellido.matches("[a-zA-Z]+")) {
        JOptionPane.showMessageDialog(null, "El apellido debe tener solo letras.");
        return;
    }

    // controlar que solo haya numeros en el telefono
    if (!telefono.matches("[0-9]+")) {
        JOptionPane.showMessageDialog(null, "El teléfono debe tener solo números.");
        return;
    }

            // creo un cliente con los datos introdidos por el usu
            Cliente cliente = new Cliente(
                    nombreField.getText(),
                    apellidoField.getText(),
                    emailField.getText(),
                    telefonoField.getText()
            );

            try {
                // guardo el cliente en un archivo
                FileManager.guardarCliente(cliente, "clientes.txt");
                JOptionPane.showMessageDialog(this, "Cliente guardado: " + cliente.getNombre() + " " + cliente.getApellido());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al guardar el cliente.");
            }
        });

        setVisible(true); // hago visible
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ClienteDialog dialog = new ClienteDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
