/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controllers.FuncionController;

import Modelos.Funcion;
import Modelos.Pelicula;

import java.sql.Date;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author rocio
 */
public class ListaFunciones extends javax.swing.JFrame {

    private DefaultListModel<Funcion> modelFunciones;
    private List<Funcion> listaFunciones;
    private FuncionController funcionController;

    /**
     * Creates new form ListaFunciones
     */
    public ListaFunciones() {
        initComponents();
        setTitle("Lista de Funciones");
        setLocationRelativeTo(null);

        funcionController = new FuncionController();
        modelFunciones = new DefaultListModel<>();
        Lista.setModel(modelFunciones);

        cargarFuncionesDesdeBD();
    }

   private void cargarFuncionesDesdeBD() {
    modelFunciones.clear();
    listaFunciones = new ArrayList<>();

    try {
        listaFunciones = funcionController.listarFunciones();
        for (Funcion f : listaFunciones) {
            modelFunciones.addElement(f);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar funciones desde la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    private void guardarCambios() {
        cargarFuncionesDesdeBD();
    }

    private String funcionToString(Funcion f) {
        return f.getPelicula() + ", " + f.getFecha() + ", " + f.getHora() + ", Sala: " + f.getSala();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JList<>();
        Editar = new javax.swing.JButton();
        Añadir = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setViewportView(Lista);

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        Añadir.setText("Añadir");
        Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Editar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Añadir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Eliminar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Salir, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Editar)
                .addGap(18, 18, 18)
                .addComponent(Eliminar)
                .addGap(18, 18, 18)
                .addComponent(Añadir)
                .addGap(18, 18, 18)
                .addComponent(Salir)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        // TODO add your handling code here
        int selectedIndex = Lista.getSelectedIndex();
        if (selectedIndex != -1) {
            Funcion f = listaFunciones.get(selectedIndex);
            String datosActuales = f.getPelicula().getId_pelicula() + "," + f.getFecha() + "," + f.getHora() + "," + f.getSala();

            String nueva = JOptionPane.showInputDialog(this, "Editar función (ID_Pelicula,Fecha(YYYY-MM-DD),Hora(HH:mm:ss),Sala):", datosActuales);

            if (nueva != null && !nueva.trim().isEmpty()) {
                try {
                    String[] partes = nueva.split(",");
                    if (partes.length != 4) {
                        throw new IllegalArgumentException("Formato incorrecto");
                    }

                    int idPelicula = Integer.parseInt(partes[0].trim());
                    LocalDate fecha = LocalDate.parse(partes[1].trim());
                    LocalTime hora = LocalTime.parse(partes[2].trim());
                    int sala = Integer.parseInt(partes[3].trim());

                    Pelicula nuevaPelicula = new Pelicula();
                    nuevaPelicula.setId_pelicula(idPelicula);

                    f.setPelicula(nuevaPelicula);
                    f.setFecha(fecha);
                    f.setHora(hora);
                    f.setSala(sala);

                    funcionController.actualizarFuncion(f);
                    guardarCambios();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Formato incorrecto. Use ID_Pelicula,Fecha,Hora,Sala\nEjemplo: 1,2025-05-26,18:30:00,3", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una función para editar.");
        }


    }//GEN-LAST:event_EditarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        int selectedIndex = Lista.getSelectedIndex();
        if (selectedIndex != -1) {
            Funcion f = listaFunciones.get(selectedIndex);
            try {
                int idFuncion = f.getId_funcion(); // ✅ Eliminar por ID de la función
                funcionController.eliminarFuncion(idFuncion);
                guardarCambios();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar la función.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una función para eliminar.");
        }


    }//GEN-LAST:event_EliminarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirActionPerformed
        // TODO add your handling code here:
        String nueva = JOptionPane.showInputDialog(this, "Nueva función (ID_Pelicula,Fecha(YYYY-MM-DD),Hora(HH:mm:ss),Sala):");
        if (nueva != null && !nueva.trim().isEmpty()) {
            try {
                String[] partes = nueva.split(",");
                if (partes.length != 4) {
                    throw new IllegalArgumentException("Formato incorrecto");
                }

                int idPelicula = Integer.parseInt(partes[0].trim());
                LocalDate fecha = LocalDate.parse(partes[1].trim());
                LocalTime hora = LocalTime.parse(partes[2].trim());
                int sala = Integer.parseInt(partes[3].trim());

                Pelicula pelicula = new Pelicula();
                pelicula.setId_pelicula(idPelicula);

                Funcion nuevaFuncion = new Funcion(fecha, pelicula, hora, sala);

                funcionController.crearFuncion(nuevaFuncion);
                guardarCambios();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Formato incorrecto. Use ID_Pelicula,Fecha,Hora,Sala", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_AñadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaFunciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaFunciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaFunciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaFunciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaFunciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Añadir;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JList<Funcion> Lista;
    private javax.swing.JButton Salir;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
